---
- name: build java project
  hosts: build
  become: yes

  roles:
    - dockerserver
    - buildserver

- name: deploy production boxfuse
  hosts: web
  become: yes

  roles:
    - dockerserver
    - webserver