---
# tasks file for webserver
- name: pull docker image
  docker_image:
    name: galend/devops_trainings:boxfuse
    source: pull

- name: run docker container
  docker_container:
    name: boxfuse-prod
    state: started
    image: galend/devops_trainings:boxfuse
    ports:
      - "8080:8080"