---
# tasks file for buildserver
- name: copy files
  copy: src=./ dest=/home/boxfuse/

- name: log into a docker registry
  docker_login:
    username: galend
    password: Ach5keile

- name: build and push image
  docker_image:
    build:
      path: /home/boxfuse
    name: galend/devops_trainings:boxfuse
    push: yes
    source: build
    state: present