---
# tasks file for buildserver
- name: install packages
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - docker.io
    - python3-pip
    - python-pip

- name: install docker
  pip: name=docker state=present

- name: copy files
  copy: src=./ dest=/home/boxfuse/

- name: log into a docker registry
  docker_login:
    username: galend
    password: Ach5keile

- name: build and push image
  docker_image:
    build:
      path: /home/boxfuse
    name: galend/devops_trainings:boxfuse
    push: yes
    source: build
    state: present