---
# tasks file for buildserver
- name: install packages
  apt: name={{item}} state=present
  update_cache: yes
  with_items:
    - docker.io
    - python-pip

- name: install docker and docker-compose
  pip: name={{item}} state=present
  with_items:
    - docker
    - docker-compose

- name: copy dockerfile
  copy: src=Dockerfile dest=/home/

- name: build maven image
  docker_image:
    build:
      path: /home
    source: build

- name: push boxfuse image to docker hub
  docker_image:
    name: tomcat:8.0-alpine
    repository: galend/devops_trainings:boxfuse
    push: yes
    source: local